python ./gam/gam.py update group gco-fy2020@student.sscps.org add member aaltido101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member abigail_farmer@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member acovene101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member amacaul101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member amontei101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member apierre101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member ashley_almeda@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member atoussa101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member atroets101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member awillia101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member bobita_atkins@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member brendan_longueil@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member cchery101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member cgambon101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member christian_francois@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member cormac_schaeferflynn@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member courtney_morin@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member cthacke101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member ctraino101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member cvallie101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member daniel_faivre@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member david_azer@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member david_david@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member destiny_greenaway@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member edor101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member ed_delphonse@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member ghicks101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member gregory_ozturk@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member hana_bowkerwickersha@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member icollin101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member imy_lei@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member iobienu101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member isak_mahegan@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member jarron_hill@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member jbarone101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member jchao101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member jdosenb101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member jhandle101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member jmoy101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member john_aiello@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member joseph_golden@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member jpiton101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member jtorsne101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member jwalsh101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member kaitlyn_grable@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member katlyn_crowley@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member keesha_pierrelouis@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member kpetion101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member kvilnai101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member kvilnai102@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member kylie_schaeferflynn@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member lbennin101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member ldohert101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member liam_mcdonald@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member maeve_carson@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member marc_chouloute@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member mckenzie_crowley@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member mhastin101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member michael_eze@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member msaint101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member mstirli101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member myles_wilson@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member nathan_tierney@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member nnortel101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member olivia_brown@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member onannar101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member patrick_vandyk@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member pmarino101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member rawsheed_nelson@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member rhill101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member rstewar101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member samantha_jocelyn@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member shannon_daly@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member slouis101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member sophia_korosidis@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member sphilip101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member sreardo101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member stanley_claude@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member tessa_beshere@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member tnazair101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member tyler_vandyk@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member xcadet101@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member zachary_hugyo@student.sscps.org
python ./gam/gam.py update group gco-fy2020@student.sscps.org add member zoe_walton@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member amanda_pamphile@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member amelia_dalton@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member aprice101@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member blake_hearn@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member bridget_clapp@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member brielle_browne@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member britney_serres@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member btempes101@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member chidera_aniagu@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member cproude101@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member daniel_vital@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member david_brown@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member edaly101@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member elizabeth_mitterando@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member emelyn_miller@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member evan_phillips@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member fionn_pinaparker@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member frantz_dumersaint@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member glaguer101@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member hannah_mullen@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member ifunanya_onwuka@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member isaiah_bernadotte@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member izabella_thibault@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member jacob_preble@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member jaden_nevarez@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member james_santiago@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member jasmine_elshurafa@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member jeremiah_derolus@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member jessica_murray@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member joseph_ciambriello@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member jose_rosario@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member joshua_antonellis@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member julia_griffin@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member kasara_elliott@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member kaylin_macmillan@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member keegan_boyle@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member khaleel_medina@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member liam_nelson@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member llamy101@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member logan_macdonald@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member lucas_whitemyer@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member madison_mcguiness@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member matthew_coleman@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member maxwell_laurent@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member molly_kirves@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member molly_sullivan@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member mundia_njoroge@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member nadeja_lachance@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member nicholas_lombardo@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member nicholas_wentzel@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member oluwagbotemi_ashley@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member portia_chambers@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member rachel_mccaffrey@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member sarah_izidore@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member senos101@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member sgriffi101@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member shyla_hartgrove@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member tovah_krasnow@student.sscps.org
python ./gam/gam.py update group gco-fy2019@student.sscps.org add member zachary_smith@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member aaron_alden@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member adam_murphy@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member alison_walsh@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member anastasia_aniagu@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member andrew_johnson@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member ashley_vincent@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member carley_pierrelouis@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member cassandra_amicangelo@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member cassie_collins@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member chinaza_o@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member christian_mathews@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member daniel_trocher@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member elyons101@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member erodrig101@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member esmith101@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member francis_sullivan@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member gabriella_rivera@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member giovanni_joseph@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member glenson_greenaway@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member henry_chao@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member ijeoma_david@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member jake_waluk@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member jared_farmer@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member jordan_lussier@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member joshua_gallion@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member jrollo101@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member jsanche101@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member katelin_morin@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member katherine_doe@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member kenny_dera@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member lapuzzi101@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member liam_carey@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member lucy_njoroge@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member madison_mirabile@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member malcolm_brown@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member mary_antonellis@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member matthew_whitman@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member max_murphy@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member mia_strahm@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member michael_maniscalco@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member mking101@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member naomi_zorrilla@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member nicholas_aniagu@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member nicole_rousseau@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member pauljoseph_blanchard@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member rleavit101@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member ryan_gallagher@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member sadiyah_archibald@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member sarah_catron@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member simmone_brown@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member stathi_tselengidis@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member tanner_demaggio@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member trevor_berry@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member veronique_milius@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member yuliya_miller@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member zachary_griffin@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member zoe_childs@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member abigail_dalton@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member alexander_mccall@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member caitlyn_laneau@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member cassidy_durkan@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member chidinma_ejiofor@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member courtney_daniels@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member daniel_freitas@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member darius_anderson@student.sscps.org
python ./gam/gam.py update group gco-fy2018@student.sscps.org add member deborah_azer@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member deion_stfleur@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member desmond_sullivan@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member dylan_shepherd@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member egoodwi101@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member elijah_dieujuste@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member emilee_manning@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member emma_goldberg@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member ethan_seal@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member evan_whitemyer@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member hallie_ferguson@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member hunter_gaenicke@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member ian_sibbald@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member izabella_vital@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member jack_freeley@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member jason_guerrier@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member jenna_murray@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member jerome_sullivan@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member jordyn_yazbeck@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member joseph_walsh@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member julia_macdougall@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member kaylee_urquizaanagnos@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member kevinray_charlot@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member kevin_jubani@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member lucas_maccormack@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member mandel_comeau@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member matthew_kirves@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member max_goldenberg@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member michael_greene@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member mike_dumersaint@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member miochy_lamour@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member molly_wright@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member nathan_middleton@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member nicholas_kennedy@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member rashad_cherant@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member robert_boudreau@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member samantha_paul@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member sarah_phanord@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member william_bracken@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member zachary_krasnow@student.sscps.org
python ./gam/gam.py update group gco-fy2017@student.sscps.org add member zain_akhtar@student.sscps.org
